name: "Setup Build Environment"
description: "Common build environment setup with caching"

inputs:
  keychain-name:
    description: "Keychain name"
    required: true
  keychain-password:
    description: "Keychain password"
    required: true
  install-swiftlint:
    description: "Whether to install SwiftLint"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: ðŸ” Create temporary keychain
      shell: bash
      env:
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
        KEYCHAIN_NAME: ${{ inputs.keychain-name }}
      run: |
        set -euo pipefail
        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME" || true
        security set-keychain-settings -lut 3600 "$KEYCHAIN_NAME"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security list-keychains -d user -s "$KEYCHAIN_NAME" "$(security default-keychain | tr -d '"')"
        security default-keychain -s "$KEYCHAIN_NAME"

    - name: ðŸ’« Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.0"
        bundler-cache: true

    - name: ðŸ›  Install Tuist (manual binary)
      shell: bash
      run: |
        TUIST_VERSION=4.118.0
        mkdir -p ~/.tuist-bin
        curl -L "https://github.com/tuist/tuist/releases/download/${TUIST_VERSION}/tuist.zip" -o tuist.zip
        unzip -o tuist.zip -d ~/.tuist-bin
        chmod +x ~/.tuist-bin/tuist
        echo "$HOME/.tuist-bin" >> $GITHUB_PATH

    - name: ðŸ“¦ Cache SPM dependencies
      uses: actions/cache@v4
      with:
        path: Tuist/.build
        key: tuist-spm-${{ runner.os }}-${{ hashFiles('Tuist/Package.resolved') }}
        restore-keys: |
          tuist-spm-${{ runner.os }}-

    - name: ðŸ›  Install tuist dependencies
      shell: bash
      run: tuist install

    - name: ðŸ“¦ Cache SwiftLint
      if: ${{ inputs.install-swiftlint == 'true' }}
      uses: actions/cache@v4
      with:
        path: /opt/homebrew/bin/swiftlint
        key: swiftlint-${{ runner.os }}-0.57.0

    - name: ðŸ§° Install SwiftLint
      if: ${{ inputs.install-swiftlint == 'true' }}
      shell: bash
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        swiftlint version
