name: Fastlane CI (PR)

on:
  pull_request:

concurrency:
  group: ci-pr-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: 🔄 Checkout source code
        uses: actions/checkout@v4

      - name: 🛠 Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          keychain-name: ${{ secrets.KEYCHAIN_NAME }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: 📦 Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: deriveddata-${{ runner.os }}-${{ hashFiles('Tuist/Package.resolved') }}
          restore-keys: |
            deriveddata-${{ runner.os }}-

      - name: 🧪 Run PR Checks (build + test)
        env:
          MATCH_REPO_URL: ${{ secrets.MATCH_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}

          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          DEV_TEAM_ID: ${{ secrets.DEV_TEAM_ID }}
          DIST_TEAM_ID: ${{ secrets.DIST_TEAM_ID }}
        run: bundle exec fastlane ci_pr

      - name: 🧹 Teardown()
        if: always()
        env:
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        run: |
          if [ -n "${KEYCHAIN_NAME:-}" ]; then
            security delete-keychain "$HOME/Library/Keychains/$KEYCHAIN_NAME" || true
          fi
